### PR TITLE
added lowercase keywords for easier search

### PR DESCRIPTION
**Pull request by romifauzi**

### CODE REVIEW

**Comment by jeanfabre** [comment]
Hi Romi.

Are we good here? or do you expect actions on my end?

Bye

 Jean

**Comment by jeanfabre** [comment]
Also, the publication has evolved, and now each action is packaged, so your changes are not automatically available via the ecosystem, Get in touch with me, if you want I can show you how to do that.

**Comment by romifauzi** [comment]
I see, sure that'd be great if you can show me. But this actions is now available on Ecosystem, I mean I can search it , and it will appear in the result list, so I'm guessing someone already packaged this action..

**Comment by romifauzi** [comment]
Also if you could show me how to package a example project onto Ecosystem, that would be great. Thanks

**Pull request merged**
